# Generated by Django 4.1.1 on 2022-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pokeapi_id", models.PositiveSmallIntegerField()),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("height", models.PositiveSmallIntegerField()),
                ("order", models.SmallIntegerField()),
                ("weight", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
